# Generated by Django 4.2.2 on 2023-07-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/files/')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=5)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('psw', models.CharField(max_length=100)),
                ('isPremium', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('documentCount', models.SmallIntegerField(default=0)),
                ('documents', models.ManyToManyField(related_name='documents', to='user.document')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isChatBox', models.BooleanField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='user.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='messages',
            field=models.ManyToManyField(related_name='messages', to='user.message'),
        ),
    ]
