# Generated by Django 4.2.2 on 2023-07-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/user_image/user_<function CustomUser.get_original_user_id at 0x0000019B365EB920>'),
        ),
    ]
